version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - recommender
    ports:
      - "5002:5002"

  recommender:
    build: .
    entrypoint: python botify/server.py
    ports:
      - "5002"
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"